import { siteContent } from "./site.ts";

/** Auction page language. Auction availability is determined by the protocol. */
export const auctionContent = {
  title: siteContent.pages.auction.title,
  biddingTitle: "$RAREFRIENDS auction",
  marketCapAtClose: "$14.35M",
  introduction: {
    completed: "The auction is complete. Review your bids, settle unspent funds, and claim purchased tokens below.",
    bidding: "A continuous clearing auction using Uniswap. Choose your maximum market cap and the amount to bid.",
  },
  completed: {
    status: "auction complete",
    summaryLabel: "auction status",
    summaryTitle: "settle and claim",
    summaryDetail: "Review your bids for settlement and token claims. New bidding is closed.",
    claimsTitle: "Your settlement and claims",
    connected: "Review your bids below. Available actions are checked against the auction contract.",
    connect: "Connect your wallet to view your bids and check settlement and claim availability.",
    marketCapLabel: "market cap at close",
    priceLabel: "final clearing price",
    claimsAction: "claim tokens",
    settleAction: "settle your bids",
    bidsAction: "your bids",
  },
  phases: {
    unfunded: "awaiting tokens",
    upcoming: "opens soon",
    live: "auction live",
    "sold-out": "sold out",
    settlement: "settlement pending",
    refunds: "refunds available",
    "claim-wait": "claims open soon",
    claim: "claims open",
  },
  countdown: {
    label: "auction countdown",
    reading: "reading auction blocks",
    loading: "loading…",
    unavailable: "unavailable",
    needsData: "Live block data is needed.",
    connect: "connect wallet",
    switch: "switch network",
    connectDetail: "Connect your wallet for live auction blocks.",
    switchDetail: "Switch your wallet to the auction network for live blocks.",
    events: { start: "auction starts in", end: "auction ends in", claim: "claims open in", complete: "auction status" },
    detail: "Auction status based on the latest available block.",
    settlement: "claims scheduled in",
    soldOut: "sold out · auction ends in",
    unfunded: { start: "awaiting tokens · start scheduled in", end: "awaiting tokens · end scheduled in", claim: "awaiting tokens · claim scheduled in" },
  },
  genesis: {
    title: "Genesis",
    description: "View the Genesis market on OpenSea to secure your position in Rare Friends.",
    conversion: "Genesis can be converted into 1,000,000 $RAREFRIENDS after paying a 100,000 $RAREFRIENDS fee.",
    action: "browse Genesis market",
  },
  bid: {
    review: "Your bid is spread over the remaining auction. You pay the clearing price, up to your limit. Any unspent amount is refunded when you settle.",
    refund: "The auction minimum was not reached. Settle your bid to receive a full refund; no tokens are purchased.",
    claim: "Claim your purchased tokens to your wallet.",
    settlement: "Update auction settlement if needed, then settle your bid and receive your unspent funds. Your wallet may request separate confirmations.",
    finalClaim: "Purchased tokens are claimed in the final step.",
    claimUnavailable: "Claim eligibility is unavailable at this block. Refresh the auction data to check again.",
    claimUnavailableLabel: "claim unavailable",
    checkingEligibility: "checking bid eligibility",
    eligibilityUnavailable: "Bid eligibility for this auction has not been configured yet.",
    commitment: "Bids stay committed until the auction ends. Outbid positions can exit earlier once the minimum raise is reached — see funds cleared in auction progress. A bid can be partially successful if it is outbid during the auction.",
    connect: "Connect wallet to view bids.",
    loading: "reading your bids…",
    unavailable: "bid data unavailable",
    empty: "no bids",
  },
  howItWorks: {
    existingTitle: "Existing bids",
    chooseTitle: "Choose a market cap",
    final: "Existing bids filled at the final clearing price while within their selected limit.",
    bidding: "Your chosen market cap sets your maximum price per token. Your bid participates over the remaining auction.",
    allocation: { title: "Continuous allocation", description: "Tokens are released throughout the auction. Bids fill at the clearing price while within their limit.", completed: "Tokens were allocated throughout the auction to bids within their selected price limit." },
    settlement: { title: "Settle and claim", description: "Settle your bid to receive unspent funds. Claim purchased tokens when claims open.", completed: "Settle your bid to receive unspent funds, then claim your purchased tokens. Your wallet checks which actions are available." },
  },
  documentation: { label: "[ about Uniswap CCA ↗ ]", href: "https://developers.uniswap.org/docs/liquidity/liquidity-launchpad/concepts/cca" },
} as const;
