/** Portfolio, rewards, and selected Friend copy. */
export const portfolioContent = {
  title: "portfolio",
  buyTokens: "buy tokens",
  showAll: "show all friends",
  loadingFriends: "loading friends…",
  noFriends: "no friends",
  unavailable: "holdings unavailable",
  disconnected: "wallet not connected",
  earning: "earning",
  inactive: "inactive",
  noEarning: "no earning friends",
  noInactive: "no inactive friends",
  temporary: "temporary · balance-dependent",
  notActivated: "not activated",
  noWallet: "no permanent wallet",
  viewWallet: "view wallet",
  fullyUpgraded: "fully upgraded",
  rewardWeight: "reward weight",
  summary: {
    inactive: "Inactive",
    earning: "Earning",
    claimable: "Claimable",
    pending: "Pending",
    apy: "Your APY",
    claimAll: "Claim all",
    claimingAll: "Claiming…",
    loading: "loading rewards…",
    unavailable: "rewards unavailable",
    estimate: "live estimate weight-based",
    apyBasis: "this cycle + pending ÷ RF you paid to activate",
    apyAnnualized: "this cycle + pending ÷ RF you paid to activate · annualized",
  },
  friend: {
    copied: "address copied",
    selectedAddress: "address selected · copy manually",
    confirmed: "transaction confirmed",
    reserveUnavailable: "Live Reserve status is unavailable.",
    rewards: "rewards to claim",
    maximumWeight: "maximum reward weight",
    upgrade: "upgrade tier",
    promote: "promote generation",
    currentWeight: "current weight",
    promotionNote: "tier reset → 0 · previous upgrades non-refundable",
    tokenCost: "token cost",
    details: "transaction details",
    wallet: "friend wallet",
    balance: "balance",
    address: "address",
    copy: "copy",
    noTokens: "no tokens",
    noNfts: "no NFTs",
    friendRewards: "unclaimed rewards excluded · claims → this wallet",
    holderRewards: "holder rewards excluded · claims → your wallet",
    notHardwired: "not hardwired",
    walletRequirement: "wallet requires hardwire",
    back: "back to friends",
    notEarning: "not earning",
    hardwireRequired: "hardwire required",
    activationRequired: "activation required",
    convert: "convert Genesis to tokens",
    conversionNotice: "Genesis → reserve · NFT, wallet control, wallet assets and future rewards surrendered",
    accruedFriendRewards: "accrued rewards remain with Genesis",
    accruedHolderRewards: "accrued holder rewards retained",
    reviewConversion: "review conversion",
  },
} as const;
