/** Wallet confirmation and transaction review copy. */
export const transactionContent = {
  review: "review action",
  loadingQuote: "Loading quote…",
  connect: "Connect your wallet to continue.",
  waitForQuote: "Wait for a live quote before confirming.",
  swapConfirmed: "Swap confirmed.",
  confirming: "confirming…",
  cancel: "cancel",
  back: "back",
  refresh: "refresh quote",
  networkFee: "network fee",
  walletFee: "wallet quote · ETH",
  confirmationNote: "Wallet confirmation per step · existing approvals reused",
  conversionAcknowledgment: "Confirm surrender of Genesis ownership, wallet control and contents, and future rewards",
  preparing: "Preparing contract steps…",
  unwrap: "Unwrap received WETH into ETH",
  swap: {
    title: "review swap",
    confirm: "confirm swap",
    quote: "live pool quote",
    pay: "you pay",
    receive: "you receive · estimated",
    minimum: "minimum received",
    fee: "pool fee · included",
    weth: "Your WETH is approved and swapped directly, with no wrapping. Each step is confirmed separately; gas is paid in ETH.",
    eth: "ETH is wrapped into WETH before swapping. Each step is confirmed separately; gas is paid in ETH.",
    sell: "The swap receives WETH. A final step unwraps the exact proceeds into ETH; existing WETH stays in your wallet.",
  },
} as const;
